/**
 * This script is executed as one of the npm postinstall hooks.
 * It puts all the core schems data into lib/schema/core.js, and
 * exports that schema data as the `schema` object.
 */

'use strict';

var fs = require('fs'),
    moment = require('moment'),
    util = require('./include/util');


/**
 * @name main:
 */
var main = function (_argc, _argv) {

  var output_path = "lib/schemas/all.js";

  /* Build file */
  var data = [
    "/* Generated by compile-schema.js on "
      + moment().local().format('YYYY-MM-DD [at] hh:mma') + ' */', ''
  ];

  /* Append JSON schema */
  data = data.concat([
    "exports.core = JSON.parse('" + util.escape_json_string(
      fs.readFileSync("schemas/core.json")
    ) + "');"
  ]);

  /* Write output */
  fs.writeFileSync(output_path, data.join("\n"));

  /* Success */
  process.stderr.write(
    "File `" + output_path + "` generated successfully.\n");

  return 0;
};


/* Entry point:
 *   Start `main` and exit with the returned status. */

process.exit(
  main(process.argv.length, process.argv)
);

