#!/bin/sh

fatal()
{
  echo 'One or more tests failed; stopping' >&2
  exit 1
}

run_tests()
{
  local driver='node_modules/nodeunit/bin/nodeunit'

  for harness in "$@"; do
    "$driver" "tests/$harness.js" || fatal
  done
}

main()
{
  npm run-script postinstall &&
  run_tests reference schema validate normalize input errors api render &&
  cd tests/functional &&
  node test.js &&
  cd ../../
}

main "$@"

