#!/bin/sh

fatal()
{
  echo 'One or more tests failed; stopping' >&2
  exit 1
}

run_tests()
{
  local driver='node_modules/nodeunit/bin/nodeunit'

  for harness in "$@"; do
    "$driver" "tests/unit/$harness.js" || fatal
  done
}

main()
{
  # Compile fixtures
  npm run-script postinstall &&
  \
  # Unit tests
  run_tests reference schema \
    validate normalize input errors api render parser expand &&
  \
  # Functional tests
  (cd tests/functional && node test.js)
}

main "$@"

